name: CI
on: [push]
jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.15, 1.16, 1.17]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
        args: -D errcheck --enable gosec

    - name: Run test
      run: |
        go test -v ./... -timeout 5s
      env:
        GO111MODULE: on
