name: CI
on: [push]
jobs:

  build:
    name: macOS
    runs-on: macos-latest
    strategy:
      matrix:
        go: [1.15]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run test
      run: |
        go test -v ./...
      env:
        GO111MODULE: on
